- hosts: localhost
  vars:
    artifactory_host: 172.31.0.42
  tasks:
    - name: Retrieve petclinic war repository
      become: yes
      become_method: sudo
      get_url: url=http://52.28.236.118:8081/artifactory/libs-snapshot-local/org/springframework/samples/spring-petclinic-eyal/1.0.0-SNAPSHOT/spring-petclinic-eyal-1.0.0-20160207.111801-1.war
           dest=/pet-clinic-docker/petclinic2.war mode=0644

    - name: Clone CourseFiles
      git: repo=https://github.com/meyals/CourseFiles dest=/pet-clinic-docker/devops/ update=no

    - name: Update docker template
      template: src=/pet-clinic-docker/devops/docker-template dest=/pet-clinic-docker/Dockerfile
          
    - name: Build docker with petclinic
      docker_image: path="/pet-clinic-docker/" name="eyal/petclinic" state=present


